# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'notebooks/**'
      - 'thesis/**'
      - 'summary/**'
      
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'notebooks/**'
      - 'thesis/**'
      - 'summary/**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt-get install gsl-bin libgsl0-dev build-essential
        python -m pip install --upgrade pip
        pip install wheel
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install git+https://github.com/pjs902/GCfit.git@binaryshift
        pip install -e .
    - name: Test with pytest
      run: |
        python -m pytest
